### ISSUE TITLE
After upgrade from ^2.9 to ^3.0 AWS S3 authentication Access denied

### ISSUE THREAD

**Issue by karmendra** [plank/laravel-mediable#173]
Hi,

With ^2.9 my upload logic to S3 works fine. upgrade the package to ^3.0, without changing any logic. I start getting this error, where AWS S3 is throwing me out with `403 Forbidden` response.

note that aws s3 bucket is not publicly accessible.

Error details

```
[2020-04-03 23:21:09] production.ERROR: Error executing "PutObject" on "https://some-bucket.s3.ap-south-1.amazonaws.com/logos/logo1-7.png"; AWS HTTP error: Client error: `PUT https://some-bucket.s3.ap-south-1.amazonaws.com/logos/logo1-7.png` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>12E2S5 (truncated...)
 AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>12E2A58A9FC7ED94</RequestId><HostId>iqbGhSF6bGu6briqYnVN+3jVYuWmcmzn9V0PF5/RZDH1z9fDyZ7JnYNn/wnqb2Szrd3RZLQMnRI=</HostId></Error> {"userId":1,"email":"superadmin@app.com","exception":"[object] (Aws\\S3\\Exception\\S3Exception(code: 0): Error executing \"PutObject\" on \"https://some-bucket.s3.ap-south-1.amazonaws.com/logos/logo1-7.png\"; AWS HTTP error: Client error: `PUT https://some-bucket.s3.ap-south-1.amazonaws.com/logos/logo1-7.png` resulted in a `403 Forbidden` response:
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>12E2A5 (truncated...)
 AccessDenied (client): Access Denied - <?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>12E2A58A9FC7ED94</RequestId><HostId>iqbGhSF6bGu6briqYnVN+3jVYuWmcmzn9V0PF5/RZEH1z9fDyZ7JnYNn/wnqb2Szrd3RZLQMnRI=</HostId></Error> at /home/forge/mrm.omniware.in/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195, GuzzleHttp\\Exception\\ClientException(code: 403): Client error: `PUT https://some-bucket.s3.ap-south-1.amazonaws.com/logos/logo1-7.png` resulted in a `403 Forbidden` response:
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>12E2S5 (truncated...)
 at /home/forge/mrm.omniware.in/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)

[stacktrace]
#0 /home/forge/mrm.omniware.in/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(100): Aws\\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\\Psr7\\Request), Object(Aws\\Command), Array)
#1 /home/forge/mrm.omniware.in/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\\WrappedHttpHandler->Aws\\{closure}(Array)
@@@

...
...

```

**Comment by karmendra** [comment]
Anyone, any thoughts. I am still stuck with this, unable to figure the reason.

**Comment by frasmage** [comment]
Hi @karmendra,

A few questions to help zero in on the issue:

- Are you able to upgrade to the latest version 4.2 instead of 3.0 (I remember there being an issue with that version)? 
- What versions of laravel and the aws/aws-sdk-php are you using?
- What operation are you trying to do with the mediable package? Can you provide a simplified code snippet?
- how is your IAM setup for that bucket?

**Comment by karmendra** [comment]
Thanks, for your response, I have not tried 4.2, as I thought a gradual update is needed... first moving to 3.0 and then 4.2.

I am currently using Laravel 5.7, aws/aws-sdk-php is 3.134

I will check and get back to you with code snippet.

There is not any specific IAM setup, in fact I am using root API access key and secret configure in laravel s3 in filesystem configuration to access the S3 bucket.

```
's3' => [
            'driver' => 's3',
            'key'    => env('S3_KEY'),
            'secret' => env('S3_SECRET'),
            'region' => env('S3_REGION'),
            'bucket' => env('BIZ_S3_BUCKET'),
            // 'visibility'=>'public'
        ],
```
